swagger:
  contact-email: lucasrodriguesmartinsoliveira@gmail.com
  contact-name: Lucas Martins
  contact-url: https://github.com/LucasMartins007
  description: Api de serviço das aplicações da Fishcount
  title: FishCount-api
  version: 1.0

controller:

  email:
    id: emailId
    parentId: pessoaId

    incluir:
      operation: Cadastrar novo email
      description: Endpoint responsavél por adicionar um email para uma pessoa

    editar:
      operation: Editar email existente
      description: Endpoint responsável por editar um email existente vinculado a uma pessoa

    listar:
      operation: Listar emails ativos da pessoa
      description: Endpoint responsável por listar todos os emails ativos da pessoa

    encontrar:
      operation: Encontrar um email por Id
      description: Endpoint responsável por encontrar um email específico pelo Id

    inativar:
      operation: Inativar um email do usuário por Id
      description: Endpoint responsável por inativar um email do usuário por Id <br>
                   O email não é excluído, somente sua propriedade ``ativo`` é setada como false

  especie:
    id: especieId

    listar:
      operation: Listar todas as espécies cadastradas no sistema
      description:  Endpoint responsável por listar as espécies de peixe já mapeadas no sistema

    encontrar:
      operation: Encontrar espécie específica pela descricão
      description: Endpoint responsável por encontrar uma espécie de peixe específica pela descricão

  login:

    autenticar:
      operation: Realizar o login da aplicação
      description: Endpoint responsável por realizar o login na aplicação e disponibilizar um token para uso em outras chamadas

  lote:
    parentId: pessoaId

    incluir:
      operation: Cadastrar novo lote
      description: Endpoint responsável por cadastrar um novo lote para a pessoa referenciada

    listar:
      operation: Listar lotes
      description: Endpoint responsável por listar todos os lotes do usuário

    atualizar:
      operation: Atualizar lotes
      description: Endpoint responsável por atualizar os dados do lote do usuário