app:
  name: fishcount-api
  version: "1.0.0"

api:
  app-name: ${app.name}
  path: /api
  version: /v1
  base-path: /${api.app-name}${api.path}${api.version}

database-config:
  development:
    server: localhost
    port: 5432
    name: fishcount
    username: admin
    password: admin

hibernate-config:
  development:
    format-sql: true
    show-sql: true
    generate-ddl: true
    ddl-auto: update


jwt.secret: FGj2herA5v2ZUaTt

spring:
  profiles:
    include:
      swagger, email_config, pix_config


---
spring:
  config.activate.on-profile: production

  application:
    name: ${app.name}

  flyway:
    locations: "classpath:/db/migration"
    url: jdbc:postgresql://${database-config.development.server}:${database-config.development.port}/${database-config.development.name}
    user: ${database-config.development.username}
    password: ${database-config.development.password}
    schemas: migration
    validate-on-migrate: true


  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: ${hibernate-config.development.show-sql}
    generate-ddl: ${hibernate-config.development.generate-ddl}
    hibernate:
      ddl-auto: ${hibernate-config.development.ddl-auto}
    properties:
      hibernate:
        format_sql: ${hibernate-config.development.format-sql}
        dialect: ${spring.jpa.database-platform}
        temp.use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
      query:
        in_clause_parameter_padding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${database-config.development.server}:${database-config.development.port}/${database-config.development.name}
    username: ${database-config.development.username}
    password: ${database-config.development.password}

    hikari:
      maximum-pool-size: 1
      connection-test-query: SELECT 1
      data-source-properties:
        "[v$session.program]": ${spring.application.name}

  mail:
    host: ${email-config.development.host}
    port: ${email-config.development.port}
    username: ${email-config.development.username}
    password: ${email-config.development.password}
    properties.mail:
      test-connection: ${email-config.development.test-connection}
      smtp:
        auth: ${email-config.development.auth}
        starttls:
          enable: ${email-config.development.enable}
          required: ${email-config.development.required}

server:
  port: 8080
  servlet:
    context-path: ${api.base-path}
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1
    mime-types: text/html,
      text/xml,
      text/plain,
      text/css,
      text/javascript,
      application/javascript,
      application/json,
      application/xml,
      application/pdf,
      image/png,
      image/jpeg,
      image/svg+xml

---


spring:
  profiles:
    active: development

  application:
    name: ${app.name}

  flyway:
    locations: "classpath:/db/migration"
    url: jdbc:postgresql://${database-config.development.server}:${database-config.development.port}/${database-config.development.name}
    user: ${database-config.development.username}
    password: ${database-config.development.password}
    schemas: migration
    validate-on-migrate: true


  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: ${hibernate-config.development.show-sql}
    generate-ddl: ${hibernate-config.development.generate-ddl}
    hibernate:
      ddl-auto: ${hibernate-config.development.ddl-auto}
    properties:
      hibernate:
        format_sql: ${hibernate-config.development.format-sql}
        dialect: ${spring.jpa.database-platform}
        temp.use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
      query:
        in_clause_parameter_padding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${database-config.development.server}:${database-config.development.port}/${database-config.development.name}
    username: ${database-config.development.username}
    password: ${database-config.development.password}

    hikari:
      maximum-pool-size: 1
      connection-test-query: SELECT 1
      data-source-properties:
        "[v$session.program]": ${spring.application.name}

  mail:
    host: ${email-config.development.host}
    port: ${email-config.development.port}
    username: ${email-config.development.username}
    password: ${email-config.development.password}
    properties.mail:
      test-connection: ${email-config.development.test-connection}
      smtp:
        auth: ${email-config.development.auth}
        starttls:
          enable: ${email-config.development.enable}
          required: ${email-config.development.required}

server:
  port: 8080
  servlet:
    context-path: ${api.base-path}
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1
    mime-types: text/html,
      text/xml,
      text/plain,
      text/css,
      text/javascript,
      application/javascript,
      application/json,
      application/xml,
      application/pdf,
      image/png,
      image/jpeg,
      image/svg+xml
